# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSvg import QSvgWidget
import re
from userdatawidget import CustomWidget
import web_emrtd_util as emrtdutil

class Ui_WebEidDialog(object):
    def setupUi(self, WebEidDialog):
        WebEidDialog.setObjectName("WebEidDialog")
        
        #WebEidDialog.setGeometry(0, 0, 550, 300)
        WebEidDialog.setMinimumSize(QtCore.QSize(570, 300))
        WebEidDialog.setMaximumSize(QtCore.QSize(570, 500))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        WebEidDialog.setSizePolicy(size_policy)
        #WebEidDialog.resize(550, 0)
        #WebEidDialog.setFixedSize(QtCore.QSize(550, 250))
        WebEidDialog.setWindowIcon(QtGui.QIcon('./images/newlogo2.png'))  # Set the icon
        WebEidDialog.setWindowTitle("Web eMRTD")
        WebEidDialog.setStyleSheet("QWidget {\n"
"background-color: white;\n"
"font-size: 14px;\n"
"font-family: \"Roboto\";\n"
"color: black;\n"
"}\n"
"QPushButton {\n"
"font-size: 17px;\n"
"border: 3px solid #EFEFEF;\n"
"border-radius: 3px;\n"
"height: 39px;\n"
"padding-left: 17px;\n"
"padding-right: 17px;\n"
"min-width: 30px;\n"
"background-color: #EFEFEF;\n"
"}\n"
"QPushButton::disabled {\n"
"background-color: #FAFAFA;\n"
"border-color: #FAFAFA;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: #DEDEDE;\n"
"border-color: #DEDEDE;\n"
"}\n"
"QPushButton::focus {\n"
"background-color: #DEDEDE;\n"
"border-color: #76767B;\n"
"}\n"
"QPushButton:default {\n"
"color: white;\n"
"background-color: #113F8E;\n"
"border-color: #113F8E;\n"
"}\n"
"QPushButton:default::disabled {\n"
"background-color: #B7C5DD;\n"
"border-color: #B7C5DD;\n"
"}\n"
"QPushButton:default::hover {\n"
"background-color: #003168;\n"
"border-color: #003168\n"
"}\n"
"QPushButton:default::focus {\n"
"background-color: #003168;\n"
"border-color: #008EEA;\n"
"}\n"
"#langButton {\n"
"color: #003168;\n"
"border: 0px;\n"
"border-radius: 3px;\n"
"max-height: 22px;\n"
"max-width: 55px;\n"
"padding-left: 0px;\n"
"padding-right: 0px;\n"
"font-size: 14px;\n"
"text-align: left;\n"
"background-position: right;\n"
"background-repeat: no-repeat;\n"
"background-origin: content;\n"
"background-image: url(:images/down.svg);\n"
"}\n"
"#langButton::hover {\n"
"background-color: #EFEFEF;\n"
"}\n"
"#langMenu {\n"
"border: 3px solid #EFEFEF;\n"
"border-radius: 3px;\n"
"background-color: #EFEFEF;\n"
"}\n"
"#langMenu > QPushButton {\n"
"color: #003168;\n"
"border: 0px;\n"
"max-height: 22px;\n"
"padding-left: 7px;\n"
"padding-right: 6px;\n"
"font-size: 14px;\n"
"text-align: left;\n"
"}\n"
"#langMenu > QPushButton:checked {\n"
"font-weight: bold;\n"
"}\n"
"CertificateButton, CertificateWidget {\n"
"border: 1px solid rgba(0,49,104,0.1);\n"
"border-radius: 4px;\n"
"min-height: 70px;\n"
"}\n"
"CertificateButton {\n"
"background-color: #F5F5F5;\n"
"}\n"
"CertificateButton:checked {\n"
"border: 2px solid #113F8E;\n"
"}\n"
"CertificateButton QWidget, CertificateWidget QWidget {\n"
"background-color: transparent;\n"
"}\n"
"CertificateButton QWidget:disabled, CertificateWidget QWidget:disabled {\n"
"color: #76767B;\n"
"}\n"
"CertificateButton #warn,  CertificateWidget #warn {\n"
"color: #CD2541;\n"
"}\n"
"QLineEdit {\n"
"border: 2px solid #113F8E;\n"
"color: #113F8E;\n"
"border-radius: 3px;\n"
"min-width: 200px;\n"
"min-height: 45px;\n"
"max-width: 200px;\n"
"max-height: 45px;\n"
"font-size: 26px;\n"
"font-weight: bold;\n"
"padding-right: 14px;\n"
"padding-left: 14px;\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"lineedit-password-character: 42;\n"
"}\n"
"QLineEdit[warning=\"true\"] {\n"
"border: 2px solid #CD2541;\n"
"color: #CD2541;\n"
"}\n"
"QDateEdit {\n"
"border: 2px solid #113F8E;\n"
"color: #113F8E;\n"
"border-radius: 3px;\n"
"min-width: 200px;\n"
"min-height: 45px;\n"
"max-width: 200px;\n"
"max-height: 45px;\n"
"font-size: 26px;\n"
"font-weight: bold;\n"
"padding-right: 14px;\n"
"padding-left: 14px;\n"
"padding-top: 0px;\n"
"padding-bottom: 0px;\n"
"}\n"
"QDateEdit[warning=\"true\"] {\n"
"border: 2px solid #CD2541;\n"
"color: #CD2541;\n"
"}\n"
"QProgressBar {\n"
"height: 30px;\n"
"background-color: #EFEFEF;\n"
"border: 1px solid #DEDEDE;\n"
"border-radius: 4px;\n"
"padding: 2px;\n"
"}\n"
"QProgressBar::chunk {\n"
"background-color: #113F8E;\n"
"border: 1px solid #003168;\n"
"border-radius: 2px;\n"
"}\n"
"#waitingPageTitleLabel, #messagePageTitleLabel, #selectCertificatePageTitleLabel, #pinInputPageTitleLabel, #aboutPageLabel {\n"
"color: #003168;\n"
"font-size: 32px;\n"
"font-weight: bold;\n"
"}\n"
"#selectCertificateDescriptionLabel, #pinInputDescriptionLabel {\n"
"max-height: 40px;\n"
"}\n"
"#selectCertificateOriginLabel, #pinInputOriginLabel, #originLabel {\n"
"color: #003168;\n"
"font-weight: bold;\n"
"max-height: 20px;\n"
"}\n"
"#pinTitleLabel, #pinErrorLabel {\n"
"max-height: 20px;\n"
"}\n"
"#pinErrorLabel {\n"
"color: #CD2541;\n"
"}\n"
"#fatalError {\n"
"border: 1px solid rgba(240,78,35,0.1);\n"
"border-radius: 3px;\n"
"min-height: 56px;\n"
"}\n"
"#aboutContent {\n"
"border: 1px solid rgba(17, 63, 142, 0.1);\n"
"border-radius: 3px;\n"
"}\n"
"#fatalErrorLabel, #aboutAlert {\n"
"color: #CD2541;\n"
"} \n"
"#helpButton {\n"
"color: #003168;\n"
"}\n"
"#aboutVersion {\n"
"color: #000000;\n"
"}\n"
"#selectAnotherCertificate {\n"
"color: #113F8E;\n"
"border: 0px;\n"
"height: 24px;\n"
"}\n")
        self.WebEidDialogLayout = QtWidgets.QVBoxLayout(WebEidDialog)
        self.WebEidDialogLayout.setContentsMargins(20, 25, 20, 20)
        self.WebEidDialogLayout.setSpacing(30)
        self.WebEidDialogLayout.setObjectName("WebEidDialogLayout")
        
        self.pageStack = QtWidgets.QStackedWidget(WebEidDialog)
        self.pageStack.setObjectName("pageStack")
        self.waitingPage = QtWidgets.QWidget()
        self.waitingPage.setObjectName("waitingPage")
        self.waitingPageLayout = QtWidgets.QVBoxLayout(self.waitingPage)
        self.waitingPageLayout.setContentsMargins(0, 0, 0, 0)
        self.waitingPageLayout.setSpacing(20)
        self.waitingPageLayout.setObjectName("waitingPageLayout")
        self.waitingPageTitleLabel = QtWidgets.QLabel(self.waitingPage)
        self.waitingPageTitleLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.waitingPageTitleLabel.setObjectName("waitingPageTitleLabel")
        self.waitingPageLayout.addWidget(self.waitingPageTitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.waitingPageLayout.addItem(spacerItem)
        self.waitingSpinner = QSvgWidget(self.waitingPage)
        self.waitingSpinner.setMinimumSize(QtCore.QSize(80, 80))
        self.waitingSpinner.setMaximumSize(QtCore.QSize(80, 80))
        self.waitingSpinner.setObjectName("waitingSpinner")
        self.waitingSpinner.load('./images/wait.svg')
        self.waitingSpinner.show()
        self.waitingPageLayout.addWidget(self.waitingSpinner, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.waitingPageLayout.addItem(spacerItem1)
        self.pageStack.addWidget(self.waitingPage)
        self.messagePage = QtWidgets.QWidget()
        self.messagePage.setObjectName("messagePage")
        self.messagePageLayout = QtWidgets.QVBoxLayout(self.messagePage)
        self.messagePageLayout.setContentsMargins(0, 0, 0, 0)
        self.messagePageLayout.setSpacing(20)
        self.messagePageLayout.setObjectName("messagePageLayout")
        self.messagePageTitleLabel = QtWidgets.QLabel(self.messagePage)
        self.messagePageTitleLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.messagePageTitleLabel.setText("Connect the card reader")
        self.messagePageTitleLabel.setWordWrap(True)
        self.messagePageTitleLabel.setObjectName("messagePageTitleLabel")
        self.messagePageLayout.addWidget(self.messagePageTitleLabel)
        self.messageInfoLayout = QtWidgets.QHBoxLayout()
        self.messageInfoLayout.setSpacing(20)
        self.messageInfoLayout.setObjectName("messageInfoLayout")
        self.cardChipIcon = QtWidgets.QLabel(self.messagePage)
        self.cardChipIcon.setMinimumSize(QtCore.QSize(50, 32))
        self.cardChipIcon.setMaximumSize(QtCore.QSize(50, 32))
        self.cardChipIcon.setPixmap(QtGui.QPixmap("./images/cardreader.svg"))
        self.cardChipIcon.setObjectName("cardChipIcon")
        self.messageInfoLayout.addWidget(self.cardChipIcon, 0, QtCore.Qt.AlignTop)
        self.connectCardLabel = QtWidgets.QLabel(self.messagePage)
        self.connectCardLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.connectCardLabel.setText("Connect the card reader")
        self.connectCardLabel.setWordWrap(True)
        self.connectCardLabel.setObjectName("connectCardLabel")
        self.messageInfoLayout.addWidget(self.connectCardLabel)
        self.messageInfoLayout.setStretch(1, 1)
        self.messagePageLayout.addLayout(self.messageInfoLayout)
        self.fatalError = QtWidgets.QWidget(self.messagePage)
        self.fatalError.setObjectName("fatalError")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fatalError)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fatalErrorIcon = QtWidgets.QLabel(self.fatalError)
        self.fatalErrorIcon.setPixmap(QtGui.QPixmap("./images/fatal.svg"))
        self.fatalErrorIcon.setObjectName("fatalErrorIcon")
        self.horizontalLayout.addWidget(self.fatalErrorIcon)
        self.fatalErrorLabel = QtWidgets.QLabel(self.fatalError)
        self.fatalErrorLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.fatalErrorLabel.setWordWrap(True)
        self.fatalErrorLabel.setObjectName("fatalErrorLabel")
        self.horizontalLayout.addWidget(self.fatalErrorLabel)
        self.horizontalLayout.setStretch(1, 1)
        self.messagePageLayout.addWidget(self.fatalError)
        self.fatalHelp = QtWidgets.QLabel(self.messagePage)
        self.fatalHelp.setOpenExternalLinks(True)
        self.fatalHelp.setObjectName("fatalHelp")
        self.messagePageLayout.addWidget(self.fatalHelp)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.messagePageLayout.addItem(spacerItem2)
        self.pageStack.addWidget(self.messagePage)
        self.selectCertificatePage = QtWidgets.QWidget()
        self.selectCertificatePage.setObjectName("selectCertificatePage")
        self.selectCertificatePageLayout = QtWidgets.QVBoxLayout(self.selectCertificatePage)
        self.selectCertificatePageLayout.setContentsMargins(0, 0, 0, 0)
        self.selectCertificatePageLayout.setSpacing(20)
        self.selectCertificatePageLayout.setObjectName("selectCertificatePageLayout")
        self.selectCertificatePageTitleLabel = QtWidgets.QLabel(self.selectCertificatePage)
        self.selectCertificatePageTitleLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.selectCertificatePageTitleLabel.setObjectName("selectCertificatePageTitleLabel")
        self.selectCertificatePageLayout.addWidget(self.selectCertificatePageTitleLabel)
        self.selectCertificateLabelLayout = QtWidgets.QGridLayout()
        self.selectCertificateLabelLayout.setHorizontalSpacing(9)
        self.selectCertificateLabelLayout.setVerticalSpacing(10)
        self.selectCertificateLabelLayout.setObjectName("selectCertificateLabelLayout")
        self.selectCertificateDescriptionLabel = QtWidgets.QLabel(self.selectCertificatePage)
        self.selectCertificateDescriptionLabel.setMinimumSize(QtCore.QSize(0, 60))
        self.selectCertificateDescriptionLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.selectCertificateDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.selectCertificateDescriptionLabel.setWordWrap(True)
        self.selectCertificateDescriptionLabel.setObjectName("selectCertificateDescriptionLabel")
        self.selectCertificateLabelLayout.addWidget(self.selectCertificateDescriptionLabel, 0, 0, 1, 2)
        self.selectCertificateOriginLabelIcon = QtWidgets.QLabel(self.selectCertificatePage)
        self.selectCertificateOriginLabelIcon.setPixmap(QtGui.QPixmap(":/images/origin.svg"))
        self.selectCertificateOriginLabelIcon.setObjectName("selectCertificateOriginLabelIcon")
        self.selectCertificateLabelLayout.addWidget(self.selectCertificateOriginLabelIcon, 1, 0, 1, 1)
        self.selectCertificateOriginLabel = QtWidgets.QLabel(self.selectCertificatePage)
        self.selectCertificateOriginLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.selectCertificateOriginLabel.setObjectName("selectCertificateOriginLabel")
        self.selectCertificateLabelLayout.addWidget(self.selectCertificateOriginLabel, 1, 1, 1, 1)
        self.selectCertificateLabelLayout.setColumnStretch(1, 1)
        self.selectCertificatePageLayout.addLayout(self.selectCertificateLabelLayout)
        self.selectCertificateInfo = QtWidgets.QVBoxLayout()
        self.selectCertificateInfo.setSpacing(6)
        self.selectCertificateInfo.setObjectName("selectCertificateInfo")
        self.selectCertificatePageLayout.addLayout(self.selectCertificateInfo)
        self.pageStack.addWidget(self.selectCertificatePage)
        
        ##CAN input design
        self.pinInputPage = QtWidgets.QWidget()
        self.pinInputPage.setObjectName("pinInputPage")
        self.pinInputPageLayout = QtWidgets.QVBoxLayout(self.pinInputPage)
        self.pinInputPageLayout.setContentsMargins(0, 0, 0, 0)
        self.pinInputPageLayout.setSpacing(20)
        self.pinInputPageLayout.setObjectName("pinInputPageLayout")
        self.pinInputPageTitleLabel = QtWidgets.QLabel(self.pinInputPage)
        self.pinInputPageTitleLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pinInputPageTitleLabel.setText("Enter CAN")
        self.pinInputPageTitleLabel.setObjectName("pinInputPageTitleLabel")
        self.pinInputPageLayout.addWidget(self.pinInputPageTitleLabel)
        self.pinInputLabelLayout = QtWidgets.QGridLayout()
        self.pinInputLabelLayout.setHorizontalSpacing(10)
        self.pinInputLabelLayout.setVerticalSpacing(9)
        self.pinInputLabelLayout.setObjectName("pinInputLabelLayout")
        self.pinInputDescriptionLabel = QtWidgets.QLabel(self.pinInputPage)
        self.pinInputDescriptionLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pinInputDescriptionLabel.setText("Please enter the 6-digit CAN (card access number) printed on the ePassport.")
        self.pinInputDescriptionLabel.setWordWrap(True)
        self.pinInputDescriptionLabel.setObjectName("pinInputDescriptionLabel")
        self.pinInputLabelLayout.addWidget(self.pinInputDescriptionLabel, 0, 0, 1, 2)
        #self.pinInputOriginLabelIcon = QtWidgets.QLabel(self.pinInputPage)
        #self.pinInputOriginLabelIcon.setPixmap(QtGui.QPixmap("./images/origin.svg"))
        #self.pinInputOriginLabelIcon.setObjectName("pinInputOriginLabelIcon")
        #self.pinInputLabelLayout.addWidget(self.pinInputOriginLabelIcon, 1, 0, 1, 1)
        #self.pinInputOriginLabel = QtWidgets.QLabel(self.pinInputPage)
        #self.pinInputOriginLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        #self.pinInputOriginLabel.setObjectName("pinInputOriginLabel")
        #self.pinInputLabelLayout.addWidget(self.pinInputOriginLabel, 1, 1, 1, 1)
        self.pinInputLabelLayout.setColumnStretch(1, 1)
        self.pinInputPageLayout.addLayout(self.pinInputLabelLayout)
        #self.pinInputPageContentLayout = QtWidgets.QGridLayout()
        #self.pinInputPageContentLayout.setHorizontalSpacing(0)
        #self.pinInputPageContentLayout.setVerticalSpacing(8)
        #self.pinInputPageContentLayout.setObjectName("pinInputPageContentLayout")
        #self.pinInputCertificateInfo = CertificateWidget(self.pinInputPage)
        #self.pinInputCertificateInfo.setObjectName("pinInputCertificateInfo")
        #self.pinInputPageContentLayout.addWidget(self.pinInputCertificateInfo, 0, 0, 1, 2)
        #self.selectAnotherCertificate = QtWidgets.QToolButton(self.pinInputPage)
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap(":/images/left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #self.selectAnotherCertificate.setIcon(icon)
        #self.selectAnotherCertificate.setIconSize(QtCore.QSize(24, 24))
        #self.selectAnotherCertificate.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        #self.selectAnotherCertificate.setObjectName("selectAnotherCertificate")
        #self.pinInputPageContentLayout.addWidget(self.selectAnotherCertificate, 1, 0, 1, 1)
        #spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.pinInputPageContentLayout.addItem(spacerItem3, 1, 1, 1, 1)
        #self.pinInputPageLayout.addLayout(self.pinInputPageContentLayout)
        self.pinLayout = QtWidgets.QVBoxLayout()
        self.pinLayout.setSpacing(10)
        self.pinLayout.setObjectName("pinLayout")
        self.pinTitleLabel = QtWidgets.QLabel(self.pinInputPage)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        
        self.pinTitleLabel.setFont(font)
        self.pinTitleLabel.setText("Enter 6-digit CAN")
        self.pinTitleLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.pinTitleLabel.setObjectName("pinTitleLabel")
        self.pinLayout.addWidget(self.pinTitleLabel)
        self.pinInput = QtWidgets.QLineEdit(self.pinInputPage)
        self.pinInput.setMaxLength(12)
        self.pinInput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.pinInput.setObjectName("pinInput")
        
        self.pinLayout.addWidget(self.pinInput, 0, QtCore.Qt.AlignLeft)
        #add alternatively link text here
        self.alternativeLabel = QtWidgets.QLabel("Alternatively, <a href='#'>enter document information</a> if the CAN cannot be located.", self.pinInputPage)
        self.alternativeLabel.setFont(font)
        self.pinLayout.addWidget(self.alternativeLabel)
        
        #add two more input here
        #Create and add the first widget
        self.birthLabel = QtWidgets.QLabel("Date of birth", self.pinInputPage)
        self.birthLabel.setFont(font)
        self.birthPicker = QtWidgets.QDateEdit(self.pinInputPage)
        #self.birthPicker.setFont(font)
        self.birthPicker.setCalendarPopup(True)
        self.birthPicker.setDisplayFormat("dd.MM.yyyy")
        #self.birthPicker.setDate(QtCore.QDate.currentDate())
        self.pinLayout.addWidget(self.birthLabel)
        self.pinLayout.addWidget(self.birthPicker)

        # Create and add the replicated widget
        self.expiryLabel = QtWidgets.QLabel("Date of expiry", self.pinInputPage)
        self.expiryLabel.setFont(font)
        self.expiryPicker = QtWidgets.QDateEdit(self.pinInputPage)
        #self.expiryPicker.setFont(font)
        self.expiryPicker.setCalendarPopup(True)
        self.expiryPicker.setDisplayFormat("dd.MM.yyyy")
        #self.expiryPicker.setDate(QtCore.QDate.currentDate())
        self.pinLayout.addWidget(self.expiryLabel)
        self.pinLayout.addWidget(self.expiryPicker)
        
        self.birthLabel.hide()
        self.birthPicker.hide()
        self.expiryLabel.hide()
        self.expiryPicker.hide()
        
        self.pinErrorLabel = QtWidgets.QLabel(self.pinInputPage)
        self.pinErrorLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.pinErrorLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pinErrorLabel.setText("Incorrect CAN, try again")
        self.pinErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pinErrorLabel.setWordWrap(True)
        self.pinErrorLabel.setObjectName("pinErrorLabel")
        self.pinLayout.addWidget(self.pinErrorLabel)
        #self.pinEntryTimeoutProgressBar = QtWidgets.QProgressBar(self.pinInputPage)
        #self.pinEntryTimeoutProgressBar.setProperty("value", 50)
        #self.pinEntryTimeoutProgressBar.setTextVisible(False)
        #self.pinEntryTimeoutProgressBar.setObjectName("pinEntryTimeoutProgressBar")
        #self.pinLayout.addWidget(self.pinEntryTimeoutProgressBar)
        #self.pinTimeRemaining = QtWidgets.QLabel(self.pinInputPage)
        #self.pinTimeRemaining.setText("Time remaining:")
        #self.pinTimeRemaining.setObjectName("pinTimeRemaining")
        #self.pinLayout.addWidget(self.pinTimeRemaining)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pinLayout.addItem(spacerItem4)
        self.pinInputPageLayout.addLayout(self.pinLayout)
        self.pageStack.addWidget(self.pinInputPage)
        
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.aboutPageLayout = QtWidgets.QVBoxLayout(self.aboutPage)
        self.aboutPageLayout.setContentsMargins(0, 0, 0, 0)
        self.aboutPageLayout.setSpacing(20)
        self.aboutPageLayout.setObjectName("aboutPageLayout")
        
        '''self.aboutTitleLayout = QtWidgets.QGridLayout()
        self.aboutTitleLayout.setHorizontalSpacing(20)
        self.aboutTitleLayout.setVerticalSpacing(20)
        self.aboutTitleLayout.setObjectName("aboutTitleLayout")
        self.aboutLogo = QtWidgets.QLabel(self.aboutPage)
        self.aboutLogo.setMinimumSize(QtCore.QSize(60, 60))
        self.aboutLogo.setMaximumSize(QtCore.QSize(100, 100))
        self.aboutLogo.setPixmap(QtGui.QPixmap("./install/appicon_128.png"))
        self.aboutLogo.setScaledContents(True)
        self.aboutLogo.setObjectName("aboutLogo")
        self.aboutTitleLayout.addWidget(self.aboutLogo, 0, 0, 2, 1)
        self.aboutPageLabel = QtWidgets.QLabel(self.aboutPage)
        self.aboutPageLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.aboutPageLabel.setObjectName("aboutPageLabel")
        self.aboutTitleLayout.addWidget(self.aboutPageLabel, 0, 1, 1, 1)
        self.aboutVersion = QtWidgets.QLabel(self.aboutPage)
        self.aboutVersion.setText("Version: 1.0.0")
        self.aboutVersion.setObjectName("aboutVersion")
        self.aboutTitleLayout.addWidget(self.aboutVersion, 1, 1, 1, 1)
        
        ##origin icon and label
        self.originLabelIcon = QtWidgets.QLabel(self.pinInputPage)
        self.originLabelIcon.setPixmap(QtGui.QPixmap("./images/origin.svg"))
        self.originLabelIcon.setObjectName("originLabelIcon")
        self.aboutTitleLayout.addWidget(self.originLabelIcon, 3, 0, 1, 1)
        self.originLabel = QtWidgets.QLabel(self.pinInputPage)
        self.originLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.originLabel.setObjectName("originLabel")
        self.aboutTitleLayout.addWidget(self.originLabel, 3, 1, 1, 1)
        self.aboutTitleLayout.setColumnStretch(2,2)
        self.aboutPageLayout.addLayout(self.aboutTitleLayout)
        '''
        ##
        '''self.aboutContent = QtWidgets.QWidget(self.aboutPage)
        self.aboutContent.setObjectName("aboutContent")
        self.aboutContentLayout = QtWidgets.QGridLayout(self.aboutContent)
        self.aboutContentLayout.setHorizontalSpacing(10)
        self.aboutContentLayout.setVerticalSpacing(20)
        self.aboutContentLayout.setObjectName("aboutContentLayout")
        self.aboutAlert = QtWidgets.QLabel(self.aboutContent)
        self.aboutAlert.setFocusPolicy(QtCore.Qt.TabFocus)
        self.aboutAlert.setWordWrap(True)
        self.aboutAlert.setObjectName("aboutAlert")
        self.aboutContentLayout.addWidget(self.aboutAlert, 1, 1, 1, 1)
        self.aboutText = QtWidgets.QLabel(self.aboutContent)
        self.aboutText.setFocusPolicy(QtCore.Qt.TabFocus)
        self.aboutText.setWordWrap(True)
        self.aboutText.setObjectName("aboutText")
        self.aboutContentLayout.addWidget(self.aboutText, 0, 1, 1, 1)
        self.aboutIcon = QtWidgets.QLabel(self.aboutContent)
        self.aboutIcon.setMinimumSize(QtCore.QSize(24, 24))
        self.aboutIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.aboutIcon.setPixmap(QtGui.QPixmap("./images/fatal.svg"))
        self.aboutIcon.setObjectName("aboutIcon")
        self.aboutContentLayout.addWidget(self.aboutIcon, 0, 0, 2, 1)
        self.aboutPageLayout.addWidget(self.aboutContent)'''
        
        self.userDataWidget = CustomWidget()
        #self.userDataWidget.setObjectName('userdatawidget')
        self.aboutPageLayout.addWidget(self.userDataWidget)
        
        self.originWidget = QtWidgets.QWidget()
        self.originLayout = QtWidgets.QHBoxLayout(self.originWidget)
        self.originLayout.setSpacing(0)
        self.originLayout.setContentsMargins(0, 0, 0, 0)
        
        self.originLabelIcon = QtWidgets.QLabel(self.pinInputPage)
        #self.originLabelIcon.setStyleSheet('border: 1px solid black; width: 20px')
        self.originLabelIcon.setFixedWidth(30)
        self.originLabelIcon.setPixmap(QtGui.QPixmap("./images/origin.svg"))
        self.originLabelIcon.setObjectName("originLabelIcon")
        self.originLayout.addWidget(self.originLabelIcon)
        
        self.originLabel = QtWidgets.QLabel(self.pinInputPage)
        #self.originLabel.setStyleSheet('border: 1px solid black;')
        self.originLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.originLabel.setObjectName("originLabel")
        self.originLayout.addWidget(self.originLabel)
        
        self.aboutHelp = QtWidgets.QLabel(self.aboutPage)
        self.aboutHelp.setOpenExternalLinks(True)
        self.aboutHelp.setObjectName("aboutHelp")
        
        self.aboutPageLayout.addWidget(self.aboutHelp)
        self.aboutPageLayout.addWidget(self.originWidget)
        
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.aboutPageLayout.addItem(spacerItem5)
        self.pageStack.addWidget(self.aboutPage)
        
        
        self.WebEidDialogLayout.addWidget(self.pageStack)
        
        
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(6)
        self.buttonLayout.setObjectName("buttonLayout")
        self.cancelButton = QtWidgets.QPushButton(WebEidDialog)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem6)
        self.helpButton = QtWidgets.QPushButton(WebEidDialog)
        self.helpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon1)
        self.helpButton.setIconSize(QtCore.QSize(30, 26))
        self.helpButton.setAutoDefault(False)
        self.helpButton.setObjectName("helpButton")
        self.buttonLayout.addWidget(self.helpButton)
        self.okButton = QtWidgets.QPushButton(WebEidDialog)
        self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./images/arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon2)
        self.okButton.setIconSize(QtCore.QSize(20, 16))
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.WebEidDialogLayout.addLayout(self.buttonLayout)
        self.pinTitleLabel.setBuddy(self.pinInput)

        self.retranslateUi(WebEidDialog)
        self.fatalError.hide()
        self.fatalHelp.hide()
        #self.messagePageSpacer.hide()
        self.connectCardLabel.setText("<b>Smart card reader not connected.</b> Please connect the smart card reader to the computer.")
        self.pageStack.setCurrentIndex(1)
        self.okButton.hide()
        self.helpButton.hide()
        QtCore.QMetaObject.connectSlotsByName(WebEidDialog)
    
    def cardReaderRemoved(self, WebEidDialog):
        self.fatalError.hide()
        self.fatalHelp.hide()
        self.cardChipIcon.setPixmap(QtGui.QPixmap("./images/cardreader.svg"))
        self.messagePageTitleLabel.setText("Connect the smart card reader")
        self.connectCardLabel.setText("<b>Smart card reader not connected.</b> Please connect the smart card reader to the computer.")
        self.pageStack.setCurrentIndex(1)
        self.resizeHeight(WebEidDialog)

    def cardReaderFound(self, WebEidDialog):
        self.fatalError.hide()
        self.fatalHelp.hide()
        self.cardChipIcon.show()
        self.connectCardLabel.show()
        self.cardChipIcon.setPixmap(QtGui.QPixmap("./images/no-id-card.svg"))
        self.messagePageTitleLabel.setText("Insert the ePassport")
        self.connectCardLabel.setText("<b>ePassport not found.</b> Please insert the ePassport into the reader.")
        self.okButton.hide()
        self.pageStack.setCurrentIndex(1)
        self.resizeHeight(WebEidDialog)
    
    def unsupportedCardError(self, errorText, WebEidDialog):
        self.fatalError.show()
        #self.fatalHelp.show()
        self.fatalErrorLabel.setText(errorText)
        #self.cardChipIcon.setPixmap(QtGui.QPixmap("./images/cardreader.svg"))
        #self.messagePageTitleLabel.setText("Connect the card reader")
        #self.connectCardLabel.setText("<b>Card reader not connected.</b> Please connect the card reader to the computer.")
        self.pageStack.setCurrentIndex(1)
        self.resizeHeight(WebEidDialog)
    
    def operationFailed(self, WebEidDialog):
        self.helpButton.show()
        self.fatalError.show()
        self.cardChipIcon.hide()
        self.connectCardLabel.hide()
        #self.fatalHelp.hide()
        #self.cardChipIcon.setPixmap(QtGui.QPixmap("./images/fatal.svg"))
        self.messagePageTitleLabel.setText("Operation failed")
        #self.connectCardLabel.setText("<b>ePassport not found.</b> Please insert the ePassport into the reader.")
        self.pageStack.setCurrentIndex(1)
        self.resizeHeight(WebEidDialog)
    
    def cardInserted(self, WebEidDialog):
        self.waitingPageTitleLabel.setText("Loading data")
        self.okButton.hide()
        self.pageStack.setCurrentIndex(0)
        self.resizeHeight(WebEidDialog)
    
    def processingCA(self, WebEidDialog):
        self.waitingPageTitleLabel.setText("Performing chip authentication")
        self.okButton.hide()
        self.pageStack.setCurrentIndex(0)
        self.resizeHeight(WebEidDialog)
    
    def enterCAN(self, WebEidDialog):
        self.pinErrorLabel.hide()
        self.pageStack.setCurrentIndex(3)
        self.okButton.setEnabled(False)
        self.okButton.show()
        self.resizeHeight(WebEidDialog)
    
    def enterBAC(self, WebEidDialog):
        #BAC input window
        self.pinTitleLabel.setText("Document number")
        self.pageStack.setCurrentIndex(3)
        #ui.pinTitleLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.pinInputPageTitleLabel.setText("Enter document information")
        self.pinInputDescriptionLabel.setText("Please enter document number, document expiry date and your birth date printed on the ePassport.")
        self.pinErrorLabel.hide()
        self.okButton.setEnabled(True)
        self.okButton.show()
        self.birthLabel.show()
        self.birthPicker.show()
        self.expiryLabel.show()
        self.expiryPicker.show()
        self.alternativeLabel.hide()
        self.pinErrorLabel.hide()
        self.resizeHeight(WebEidDialog)
    
    def incorrectCAN(self, WebEidDialog):
        self.pinErrorLabel.show()
        self.pageStack.setCurrentIndex(3)
        #self.okButton.setEnabled(False)
        #self.okButton.clicked.connect(lambda: verifyCAN(ui.pinInput.text()))
        self.okButton.show()
        self.resizeHeight(WebEidDialog)
    
    def userDataWindow(self, WebEidDialog, docType, userPhoto, countryCode, dataDict):
        self.pageStack.setCurrentIndex(4)
        self.okButton.show()
        self.userDataWidget.insertUserDocPhoto(docType, userPhoto)
        self.userDataWidget.insertFlagCountry(countryCode)
        self.userDataWidget.insertDataWidgets(dataDict)
        self.userDataWidget.roundFrame()
        self.resizeHeight(WebEidDialog)
    
    def resizeHeight(self, WebEidDialog):
        self.pageStack.setFixedHeight(self.pageStack.currentWidget().sizeHint().height())
        #print('[+] user data confirm window width:', self.userDataWidget.sizeHint().width())
        #print('[+] user data confirm window height:', self.userDataWidget.sizeHint().height())
        WebEidDialog.adjustSize()
    
    def viewerVerifierMode(self, WebEidDialog):
        #modify viewer verifier mode
        self.cancelButton.setText("Open")
        self.cancelButton.show()
        self.okButton.setText("Save")
        self.okButton.setIcon(QtGui.QIcon())
        self.originLabel.hide()
        self.originLabelIcon.hide()
        self.aboutHelp.hide()
        
    def retranslateUi(self, WebEidDialog):
        _translate = QtCore.QCoreApplication.translate
        self.waitingPageTitleLabel.setText(_translate("WebEidDialog", "Waiting for card"))
        self.fatalErrorLabel.setText(_translate("WebEidDialog", "Operation failed. Click <b>Help</b> button to access the log files for more detailed information."))
        self.fatalHelp.setText(_translate("WebEidDialog", "Get help here: <a href=\"https://www.id.ee\">id.ee</a>"))
        self.selectCertificatePageTitleLabel.setText(_translate("WebEidDialog", "Select a certificate"))
        self.selectCertificateDescriptionLabel.setText(_translate("WebEidDialog", "By choosing the certificate, I agree to the transfer of my name and personal identification code to the service provider."))
        #self.selectAnotherCertificate.setText(_translate("WebEidDialog", "Select another certificate"))
        #self.aboutPageLabel.setText(_translate("WebEidDialog", "About Web eID"))
        #self.aboutAlert.setText(_translate("WebEidDialog", "Web eID extension is disabled. The extension must be enabled in the web browser to authenticate and sign with an ID-card."))
        #self.aboutText.setText(_translate("WebEidDialog", "<b>This is a companion application to the Web eID browser extension</b> and cannot be used independently. <p>To uninstall the extension, remove this application.</p>"))
        self.aboutHelp.setText(_translate("WebEidDialog", "Get help here: <a href=\"https://www.id.ee\">id.ee</a>"))
        self.cancelButton.setText(_translate("WebEidDialog", "Cancel"))
        self.helpButton.setText(_translate("WebEidDialog", "Help"))
        self.okButton.setText(_translate("WebEidDialog", "Confirm"))

#from certificatewidget.hpp import CertificateWidget
#import webeidresources

#def on_button_clicked(button):
#    print("%s button clicked!" % button)

#Design confirmation window
'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WebEidDialog = QtWidgets.QDialog()
    ui = Ui_WebEidDialog()
    ui.setupUi(WebEidDialog)
    WebEidDialog.show()
    
    ui.originLabel.setText('https://web-emrtd.eu')
    ui.aboutLogo.hide()
    ui.aboutText.setText('<p>text</p>')
    ui.aboutHelp.setWordWrap(True)
    ui.aboutHelp.setText('agree')
    ui.aboutPageLabel.setText('a b (c)')
    ui.aboutVersion.setText('expiry')
    ui.aboutAlert.hide()
    ui.aboutIcon.hide()
    ui.pageStack.setCurrentIndex(4)
    ui.resizeHeight(WebEidDialog)
    
    sys.exit(app.exec_())
'''

'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WebEidDialog = QtWidgets.QDialog()
    ui = Ui_WebEidDialog()
    ui.setupUi(WebEidDialog)
    WebEidDialog.show()
    ui.viewerVerifierMode(WebEidDialog)
    ui.pageStack.setCurrentIndex(4)
    sys.exit(app.exec_())'''

#Design user data confirm window
'''if __name__ == "__main__":
    import sys
    import web_emrtd as weid
    
    app = QtWidgets.QApplication(sys.argv)
    WebEidDialog = QtWidgets.QDialog()
    ui = Ui_WebEidDialog()
    ui.setupUi(WebEidDialog)
    WebEidDialog.show()
    
    ui.originLabel.setText('https://web-emrtd.eu')
    ui.aboutHelp.setWordWrap(True)
    confirmText = "By confirming, I agree to the transfer of my personal data listed above (<b>including facial photo</b>) to the service provider."
    ui.aboutHelp.setText(confirmText)
    
    #MRZ test data
    testData = "YV1fH1pJUkVTVEJFMDEzNjYyNjUzOTQwMTAxMDA2Nzw8PDw5NDAxMDEzTTI1MTExOTlUVVI8PDw8PDw8PDw8PDlLQVBJU0laPDxERU5JWkFMUDw8PDw8PDw8PDw8PDw="
    userPhoto = b''
    parsedMRZ = emrtdutil.parse_DG1(testData)
    
    ui.userDataWindow(WebEidDialog, parsedMRZ['doctype'], userPhoto, parsedMRZ['issuing_state'], parsedMRZ)
    
    sys.exit(app.exec_())
'''